package ckalkan

const (
	unknownEnglishErrorLabel = "unknown error code"
	unknownRussianErrorLabel = "неизвестный код ошибки"
)

//nolint:gosec,gochecknoglobals
var englishErrorLabels = map[ErrorCode]string{
	ErrorOK:                           "no error",
	ErrorInit:                         "initialization error",
	ErrorReadPKCS12:                   "cannot read PKCS#12 file",
	ErrorOpenPKCS12:                   "cannot open PKCS#12 file",
	ErrorInvalidPropID:                "invalid certificate property identifier",
	ErrorBufferTooSmall:               "buffer is too small",
	ErrorCertParse:                    "certificate parse error",
	ErrorInvalidFlag:                  "invalid flag",
	ErrorOpenFile:                     "cannot open file",
	ErrorInvalidPassword:              "invalid password",
	ErrorCertWrongDate:                "invalid certificate date",
	ErrorCertExpired:                  "certificate expired",
	ErrorIsNotCACert:                  "certificate is not a CA certificate",
	ErrorMemory:                       "memory allocation error",
	ErrorCheckChain:                   "certificate chain validation error",
	ErrorCACertKeyUsage:               "invalid CA certificate key usage",
	ErrorValidType:                    "invalid validation type",
	ErrorBadCRLFormat:                 "invalid CRL format",
	ErrorLoadCRL:                      "cannot load CRL",
	ErrorLoadCRLs:                     "cannot load CRLs",
	ErrorUnknownAlg:                   "unknown algorithm",
	ErrorKeyNotFound:                  "private key not found",
	ErrorSignInit:                     "signature initialization error",
	ErrorSign:                         "signature error",
	ErrorEncode:                       "encoding error",
	ErrorInvalidFlags:                 "invalid flags",
	ErrorCertNotFound:                 "certificate not found",
	ErrorVerifySign:                   "signature verification error",
	ErrorBase64Decode:                 "Base64 decode error",
	ErrorUnknownCMSFormat:             "unknown CMS format",
	ErrorGetHash:                      "hash retrieval error",
	ErrorCACertNotFound:               "CA certificate not found",
	ErrorXMLSecInit:                   "xmlsec initialization error",
	ErrorLoadTrustedCerts:             "trusted certificates loading error",
	ErrorSignInvalid:                  "invalid signature",
	ErrorNoSignFound:                  "signature not found",
	ErrorDecode:                       "decode error",
	ErrorXMLParse:                     "XML parse error",
	ErrorXMLAddID:                     "XML ID add error",
	ErrorXMLInternal:                  "internal XML error",
	ErrorXMLSetSign:                   "XML signature setup error",
	ErrorOpenSSL:                      "OpenSSL error",
	ErrorEngineInit:                   "engine initialization error",
	ErrorNoTokenFound:                 "token not found",
	ErrorOCSPAddCert:                  "OCSP request certificate add error",
	ErrorOCSPParseURL:                 "OCSP URL parse error",
	ErrorOCSPAddHost:                  "OCSP host add error",
	ErrorOCSPReq:                      "OCSP request creation error",
	ErrorOCSPConnection:               "OCSP connection error",
	ErrorVerifyNoData:                 "no data to verify",
	ErrorIDAttrNotFound:               "ID attribute not found",
	ErrorIDRange:                      "invalid ID range or index",
	ErrorXMLKeyDup:                    "duplicate XML key",
	ErrorXMLKeyCreate:                 "XML key creation error",
	ErrorReaderNotFound:               "reader not found",
	ErrorGetCertProp:                  "certificate property retrieval error",
	ErrorSignFormat:                   "unknown signature format",
	ErrorInDataFormat:                 "unknown input data format",
	ErrorOutDataFormat:                "unknown output data format",
	ErrorVerifyInit:                   "verification initialization error",
	ErrorVerify:                       "verification error",
	ErrorHash:                         "hashing error",
	ErrorSignHash:                     "hash signing error",
	ErrorCACertsNotFound:              "CA certificates not found",
	ErrorCertTimeInvalid:              "certificate validity time is invalid",
	ErrorConvert:                      "conversion error",
	ErrorTSACreateQuery:               "TSA query creation error",
	ErrorCreateObj:                    "ASN.1 object creation error",
	ErrorCreateNonce:                  "nonce creation error",
	ErrorHTTP:                         "HTTP error",
	ErrorCADESBESFailed:               "CAdES-BES processing error",
	ErrorCADESTFailed:                 "CAdES-T processing error",
	ErrorNoTSAToken:                   "TSA token is absent",
	ErrorInvalidDigestLen:             "invalid digest length",
	ErrorGenRand:                      "random data generation error",
	ErrorSoapNS:                       "SOAP namespace error",
	ErrorGetPubKey:                    "public key retrieval error",
	ErrorGetCertInfo:                  "certificate information retrieval error",
	ErrorFileRead:                     "file read error",
	ErrorCheck:                        "check failed or hash mismatch",
	ErrorZipExtract:                   "ZIP extraction error",
	ErrorNoManifestFile:               "MANIFEST file not found",
	ErrorVerifyTSHash:                 "TSA token hash verification error",
	ErrorXADESTFailed:                 "XAdES-T verification error",
	ErrorOCSPRespStatMalformedRequest: "OCSP: malformed request",
	ErrorOCSPRespStatInternalError:    "OCSP: internal error",
	ErrorOCSPRespStatTryLater:         "OCSP: try later",
	ErrorOCSPRespStatSigRequired:      "OCSP: signature required",
	ErrorOCSPRespStatUnauthorized:     "OCSP: unauthorized request",
	ErrorVerifyIssuerSerialV2:         "IssuerSerialV2 verification error",
	ErrorOCSPCheckCertFromResp:        "certificate check from OCSP response failed",
	ErrorCRLExpired:                   "CRL expired",
	ErrorLibraryNotInitialized:        "library is not initialized",
	ErrorEngineLoad:                   "engine loading error",
	ErrorParam:                        "invalid parameters",
	ErrorCertStatusOK:                 "certificate status: valid",
	ErrorCertStatusRevoked:            "certificate status: revoked",
	ErrorCertStatusUnknown:            "certificate status: unknown",
}

//nolint:gosec,gochecknoglobals
var russianErrorLabels = map[ErrorCode]string{
	ErrorOK:                           "нет ошибки",
	ErrorInit:                         "ошибка инициализации",
	ErrorReadPKCS12:                   "невозможно прочитать файл PKCS#12",
	ErrorOpenPKCS12:                   "невозможно открыть файл PKCS#12",
	ErrorInvalidPropID:                "недопустимый идентификатор свойства сертификата",
	ErrorBufferTooSmall:               "буфер слишком мал",
	ErrorCertParse:                    "ошибка разбора сертификата",
	ErrorInvalidFlag:                  "недопустимый флаг",
	ErrorOpenFile:                     "невозможно открыть файл",
	ErrorInvalidPassword:              "неправильный пароль",
	ErrorCertWrongDate:                "некорректная дата сертификата",
	ErrorCertExpired:                  "сертификат истек",
	ErrorIsNotCACert:                  "сертификат не является сертификатом УЦ",
	ErrorMemory:                       "ошибка выделения памяти",
	ErrorCheckChain:                   "ошибка построения/проверки цепочки сертификатов",
	ErrorCACertKeyUsage:               "некорректное использование ключа сертификата УЦ",
	ErrorValidType:                    "недопустимый тип валидации",
	ErrorBadCRLFormat:                 "некорректный формат CRL",
	ErrorLoadCRL:                      "невозможно загрузить CRL",
	ErrorLoadCRLs:                     "невозможно загрузить CRL-ы",
	ErrorUnknownAlg:                   "неизвестный алгоритм",
	ErrorKeyNotFound:                  "приватный ключ не найден",
	ErrorSignInit:                     "ошибка инициализации подписи",
	ErrorSign:                         "ошибка подписи",
	ErrorEncode:                       "ошибка кодирования",
	ErrorInvalidFlags:                 "недопустимые флаги",
	ErrorCertNotFound:                 "сертификат не найден",
	ErrorVerifySign:                   "ошибка проверки подписи",
	ErrorBase64Decode:                 "ошибка декодирования Base64",
	ErrorUnknownCMSFormat:             "неизвестный формат CMS",
	ErrorGetHash:                      "ошибка получения хэша",
	ErrorCACertNotFound:               "сертификат УЦ не найден",
	ErrorXMLSecInit:                   "ошибка инициализации xmlsec",
	ErrorLoadTrustedCerts:             "ошибка загрузки доверенных сертификатов",
	ErrorSignInvalid:                  "недопустимая подпись",
	ErrorNoSignFound:                  "подпись не найдена",
	ErrorDecode:                       "ошибка декодирования",
	ErrorXMLParse:                     "ошибка разбора XML",
	ErrorXMLAddID:                     "ошибка добавления XML ID",
	ErrorXMLInternal:                  "внутренняя ошибка XML",
	ErrorXMLSetSign:                   "ошибка установки XML-подписи",
	ErrorOpenSSL:                      "ошибка OpenSSL",
	ErrorEngineInit:                   "ошибка инициализации engine",
	ErrorNoTokenFound:                 "токен не найден",
	ErrorOCSPAddCert:                  "ошибка добавления сертификата в OCSP-запрос",
	ErrorOCSPParseURL:                 "ошибка разбора OCSP URL",
	ErrorOCSPAddHost:                  "ошибка добавления OCSP host",
	ErrorOCSPReq:                      "ошибка формирования OCSP-запроса",
	ErrorOCSPConnection:               "ошибка соединения с OCSP",
	ErrorVerifyNoData:                 "нет данных для проверки",
	ErrorIDAttrNotFound:               "атрибут ID не найден",
	ErrorIDRange:                      "некорректный диапазон/номер ID",
	ErrorXMLKeyDup:                    "дублирование XML-ключа",
	ErrorXMLKeyCreate:                 "ошибка создания XML-ключа",
	ErrorReaderNotFound:               "ридер не найден",
	ErrorGetCertProp:                  "ошибка получения свойства сертификата",
	ErrorSignFormat:                   "неизвестный формат подписи",
	ErrorInDataFormat:                 "неизвестный формат входных данных",
	ErrorOutDataFormat:                "неизвестный формат выходных данных",
	ErrorVerifyInit:                   "ошибка инициализации проверки",
	ErrorVerify:                       "ошибка проверки",
	ErrorHash:                         "ошибка хэширования",
	ErrorSignHash:                     "ошибка подписи хэша",
	ErrorCACertsNotFound:              "сертификаты УЦ не найдены",
	ErrorCertTimeInvalid:              "срок действия сертификата недействителен",
	ErrorConvert:                      "ошибка преобразования",
	ErrorTSACreateQuery:               "ошибка создания TSA-запроса",
	ErrorCreateObj:                    "ошибка создания объекта ASN.1",
	ErrorCreateNonce:                  "ошибка создания nonce",
	ErrorHTTP:                         "ошибка HTTP",
	ErrorCADESBESFailed:               "ошибка CAdES-BES",
	ErrorCADESTFailed:                 "ошибка CAdES-T",
	ErrorNoTSAToken:                   "TSA-токен отсутствует",
	ErrorInvalidDigestLen:             "некорректная длина дайджеста",
	ErrorGenRand:                      "ошибка генерации случайных данных",
	ErrorSoapNS:                       "ошибка SOAP namespace",
	ErrorGetPubKey:                    "ошибка получения публичного ключа",
	ErrorGetCertInfo:                  "ошибка получения информации о сертификате",
	ErrorFileRead:                     "ошибка чтения файла",
	ErrorCheck:                        "ошибка проверки/несовпадение хэша",
	ErrorZipExtract:                   "ошибка извлечения ZIP",
	ErrorNoManifestFile:               "файл MANIFEST не найден",
	ErrorVerifyTSHash:                 "ошибка проверки хэша TSA-токена",
	ErrorXADESTFailed:                 "ошибка проверки XAdES-T",
	ErrorOCSPRespStatMalformedRequest: "OCSP: неправильный запрос",
	ErrorOCSPRespStatInternalError:    "OCSP: внутренняя ошибка",
	ErrorOCSPRespStatTryLater:         "OCSP: попробуйте позже",
	ErrorOCSPRespStatSigRequired:      "OCSP: требуется подпись запроса",
	ErrorOCSPRespStatUnauthorized:     "OCSP: запрос не авторизован",
	ErrorVerifyIssuerSerialV2:         "ошибка проверки IssuerSerialV2",
	ErrorOCSPCheckCertFromResp:        "ошибка проверки сертификата из OCSP-ответа",
	ErrorCRLExpired:                   "CRL истек",
	ErrorLibraryNotInitialized:        "библиотека не инициализирована",
	ErrorEngineLoad:                   "ошибка загрузки engine",
	ErrorParam:                        "некорректные параметры",
	ErrorCertStatusOK:                 "статус сертификата: действителен",
	ErrorCertStatusRevoked:            "статус сертификата: отозван",
	ErrorCertStatusUnknown:            "статус сертификата: неизвестен",
}

func errorLabelsForLanguage(language ErrorLanguage) (map[ErrorCode]string, string) {
	switch language {
	case ErrorLanguageRussian:
		return russianErrorLabels, unknownRussianErrorLabel
	default:
		return englishErrorLabels, unknownEnglishErrorLabel
	}
}
